GET http://localhost:8080/api/v1/patients
Cookie: auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZpZG1lZGlhQGdtYWlsLmNvbSIsImV4cCI6MTc0NzQxOTQ2NSwiaWF0IjoxNzQ3MTYwMjY1LCJuYmYiOjE3NDcxNjAyNjUsInJvbGUiOiJTdXBlckFkbWluIiwic3ViIjoiNGNmZjFkYmEtZGRjMS00YzAwLThiNmYtZTRlZjY5YTkzM2U1In0.1KGufjzcTgARUZ_V1r9MvK2E8etEXJxwp9eEErvek6E