GET http://localhost:8080/api/v1/auth/profile
Cookie: auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZpZG1lZGlhQGdtYWlsLmNvbSIsImV4cCI6MTc0NTU4NTUzOCwiaWF0IjoxNzQ1MzI2MzM4LCJuYmYiOjE3NDUzMjYzMzgsInJvbGUiOiJTdXBlckFkbWluIiwic3ViIjoiNGNmZjFkYmEtZGRjMS00YzAwLThiNmYtZTRlZjY5YTkzM2U1In0.5eHKRHHp3CzrPGQEyV4O-tx-TOOH4-7tLfAaWkn6IX4