GET http://localhost:8080/api/v1/users/profile
Cookie: auth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDUwNjE1NzgsImlhdCI6MTc0NDgwMjM3OCwibmJmIjoxNzQ0ODAyMzc4LCJzdWIiOiJkYTc0MmQwZi1mNDQ4LTRjNzctYTY0OC1iNmZlMDY2MzQyNjAifQ.NdPwFaDBSaQpaZSnI_pZSW7lIslqjDmvFIQj4lxTgrI